language: node_js
<% if (sonar) { %>
addons:
  sonarcloud:
    organization: <%= sonar.orga %>
<% } %>
node_js:
- '8'
script:
- npm run test
<% if (sonar) { %>
after_success:
- sonar-scanner
<% } %>
<% if (npm) { %>
before_deploy:
- npm run build
deploy:
  provider: npm
  email: <%= npm.email %>
  skip_cleanup: true
  tag: next
  on:
    tags: true
  api_key:
    secure: none
<% } %>
