name: "Auto-release"

on:
  push:
    branches: [main]
    paths-ignore:
      - "docs/**"

permissions: write-all

jobs:
  analyze:
    name: Auto-release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup git user information
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Install deps
        run: yarn

      - name: Create version
        run: yarn run new-version

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

      - name: Build project
        run: yarn run build
